### ISSUE TITLE
Issue with "subscriptions" count

### ISSUE THREAD

**Issue by asmvik** [splintah/chunkwm-rs-template#1]
https://github.com/splintah/chunkwm-rs-template/blob/master/plugin/plugin.cpp#L107

I believe this will fail if you pass it a pointer rather than an array, as the count is calculated as follows: `Plugin->SubscriptionCount = sizeof(Sub) / sizeof(*Sub);`

This is probably something that I'll have to change in the ABI.

**Comment by splintersuidman** [comment]
Oh yeah, forgotten about that, thank you for pointing it out.
I am going to create a struct that holds both the length and the pointer to the array (similar to [what I did the other way around](https://github.com/splintah/chunkwm-rs/blob/8f3e853de6cff58bbb4c459ffa72cb34f1c8aa9f/chunkwm-lib/accessibility/application.mm#L18)).
